language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
    - 0.12
    - 0.11
    - 0.10
branches:
only:
    - dev
    - master
# Install prerequisites
before_script:
    - npm install -g gulp
    - npm install -g istanbul
    - npm install -g mocha
# Run `gulp coveralls` to send data to Coveralls
after_success:
    - gulp coveralls
